export const natalCompositionRules = [
  {
    id: "official_resource_support",
    version: "natal-composition-rule-v1",
    title: "官印承接",
    role: "support",
    status: "derived",
    importance: "high",
    baseConfidence: "medium",
    priority: 84,
    tags: ["官杀", "印星", "承接", "结构"],
    domains: ["career", "self", "parents"],
    thresholds: {
      officerMinWeightedCount: 0,
      resourceMinWeightedCount: 0,
      monthParticipationPriorityBonus: 8,
      monthParticipationConfidence: "high",
    },
    brief:
      "官杀与印星在原局均有落点，可作为规则压力、学习资质与承接能力之间的结构线索。",
    reasoning: [
      "官杀组与印星组的 weightedCount 均大于阈值。",
      "月干或月支主气参与时，说明该结构更贴近月令与主轴，需要优先复核。",
    ],
  },
  {
    id: "wealth_official_resource_trace",
    version: "natal-composition-rule-v1",
    title: "财官印承接线索",
    role: "conditional",
    status: "conditional",
    importance: "medium",
    baseConfidence: "medium",
    priority: 72,
    tags: ["财星", "官杀", "印星", "承接线索"],
    domains: ["wealth", "career", "self"],
    thresholds: {
      wealthMinWeightedCount: 0,
      officerMinWeightedCount: 0,
      resourceMinWeightedCount: 0,
    },
    brief:
      "财星、官杀与印星三类资源均有落点，提示资源、规则与承接能力之间存在可复核线索。",
    reasoning: [
      "财星组、官杀组、印星组 weightedCount 均大于阈值。",
      "该规则只记录三类资源有落点，不直接判定形成完整生化链。",
    ],
  },
  {
    id: "day_pillar_repetition",
    version: "natal-composition-rule-v1",
    title: "日柱参与伏吟",
    role: "tension",
    status: "derived",
    importance: "medium",
    baseConfidence: "high",
    priority: 78,
    tags: ["日柱", "伏吟", "重复", "复核"],
    domains: ["self", "relationship"],
    thresholds: {},
    brief:
      "日柱与其他柱位干支完全相同，提示自我位置与对应柱位之间存在重复回响，需要结合全局复核。",
    reasoning: [
      "由 pillar_stem 与 pillar_branch 重建四柱。",
      "日柱与年、月、时任一柱的天干和地支同时相同。",
    ],
  },
  {
    id: "spouse_palace_relation_tension",
    version: "natal-composition-rule-v1",
    title: "日支关系牵动",
    role: "tension",
    status: "derived",
    importance: "medium",
    baseConfidence: "medium",
    priority: 76,
    tags: ["日支", "关系", "张力", "复核"],
    domains: ["relationship", "self"],
    thresholds: {
      tensionRelationTypes: [
        "branch_clash",
        "branch_punish",
        "branch_self_punish",
        "branch_harm",
        "branch_break",
        "刑",
        "冲",
        "害",
        "破",
      ],
    },
    brief:
      "日支参与刑、冲、害、破类关系，提示关系宫位被牵动，可作为关系互动与边界议题的复核点。",
    reasoning: [
      "relation.has_relation 中存在 day branch 参与者。",
      "relationType 属于刑、冲、害、破的张力关系集合。",
    ],
  },
  {
    id: "peer_wealth_competition",
    version: "natal-composition-rule-v1",
    title: "比劫牵财",
    role: "conditional",
    status: "conditional",
    importance: "medium",
    baseConfidence: "medium",
    priority: 70,
    tags: ["比劫", "财星", "资源", "边界"],
    domains: ["wealth", "network", "self"],
    thresholds: {
      peerMinWeightedCount: 0,
      wealthMinWeightedCount: 0,
    },
    brief:
      "比劫与财星均有实际权重，提示资源、合作、分配和边界之间存在互动线索。",
    reasoning: [
      "比肩或劫财 weightedCount 大于阈值。",
      "正财或偏财 weightedCount 大于阈值。",
    ],
  },
  {
    id: "resource_heavy_output_weak",
    version: "natal-composition-rule-v1",
    title: "印重食伤弱",
    role: "conditional",
    status: "conditional",
    importance: "medium",
    baseConfidence: "medium",
    priority: 68,
    tags: ["印星", "食伤", "表达", "条件"],
    domains: ["self", "career", "learning"],
    thresholds: {
      outputWeakMaxWeightedCount: 0.4,
      resourceToOutputRatioMin: 2,
      resourceMinWeightedCount: 1,
    },
    brief:
      "印星权重明显高于食伤组，提示吸收、资质与表达输出之间存在条件差异，需要结合通关和现实应象复核。",
    reasoning: [
      "印星组 weightedCount 达到规则阈值。",
      "食伤组 weightedCount 处于较弱阈值内，且印星相对食伤达到比例要求。",
    ],
  },
  {
    id: "element_bias_visible",
    version: "natal-composition-rule-v1",
    title: "五行偏性明显",
    role: "conditional",
    status: "derived",
    importance: "medium",
    baseConfidence: "medium",
    priority: 66,
    tags: ["五行", "偏性", "复核"],
    domains: ["self", "health", "temperament"],
    thresholds: {
      acceptedBiasLevels: ["偏颇", "明显偏颇", "偏枯"],
      requireDominantElements: true,
      requireWeakestElements: true,
    },
    brief:
      "五行偏性、偏旺元素与偏弱元素同时可见，提示结构分布不均，需要结合调候和通关条件复核。",
    reasoning: [
      "bias_level、dominant_elements、weakest_elements 三类事实同时命中。",
      "该规则只记录五行分布形态，不直接对应具体疾病。",
    ],
  },
  {
    id: "month_command_official",
    version: "natal-composition-rule-v1",
    title: "月令官星",
    role: "core",
    status: "derived",
    importance: "high",
    baseConfidence: "high",
    priority: 82,
    tags: ["月令", "官杀", "主轴"],
    domains: ["career", "self"],
    thresholds: {
      acceptedTenGods: ["正官", "七杀"],
    },
    brief:
      "月支主气为官杀，提示规则、责任或约束议题进入月令主轴，需要结合日主承载与印比财食配置复核。",
    reasoning: [
      "month 的 pillar_branch_main_ten_god 为正官或七杀。",
      "该规则只记录月令主气结构，不单凭月令判断事业结果。",
    ],
    titleByTenGod: {
      正官: "月令正官",
      七杀: "月令七杀",
    },
  },
];
