export const natalCompositionRules = [
  {
    id: "official_resource_support",
    version: "natal-composition-rule-v1",
    title: "官印承接",
    role: "core",
    status: "derived",
    importance: "high",
    baseConfidence: "medium",
    priority: 84,
    tags: ["官杀", "印星", "承接", "结构"],
    domains: ["career", "self", "parents"],
    thresholds: {
      officerMinWeightedCount: 0.7,
      resourceMinWeightedCount: 0.7,
      requireStructuralAnchor: true,
      monthParticipationPriorityBonus: 8,
      monthParticipationConfidence: "high",
    },
    brief:
      "官杀与印星在原局均有落点，可作为规则压力、学习资质与承接能力之间的结构线索。",
    reasoning: [
      "官杀组与印星组的 weightedCount 均达到规则阈值。",
      "月干、月支主气或年干出现官杀印锚点时，说明该结构有明确柱位承接，需要优先复核。",
    ],
  },
  {
    id: "wealth_official_resource_trace",
    version: "natal-composition-rule-v1",
    title: "财官印承接线索",
    role: "core",
    status: "conditional",
    importance: "medium",
    baseConfidence: "medium",
    priority: 72,
    tags: ["财星", "官杀", "印星", "承接线索"],
    domains: ["wealth", "career", "self"],
    thresholds: {
      wealthMinWeightedCount: 0.7,
      officerMinWeightedCount: 0.7,
      resourceMinWeightedCount: 0.7,
    },
    brief:
      "财星、官杀与印星三类资源均有落点，提示资源、规则与承接能力之间存在可复核线索。",
    reasoning: [
      "财星组、官杀组、印星组 weightedCount 均大于阈值。",
      "该规则只记录三类资源有落点，不直接判定形成完整生化链。",
    ],
  },
  {
    id: "day_pillar_repetition",
    version: "natal-composition-rule-v1",
    title: "日柱参与伏吟",
    role: "tension",
    status: "derived",
    importance: "medium",
    baseConfidence: "high",
    priority: 78,
    tags: ["日柱", "伏吟", "重复", "复核"],
    domains: ["self", "spouse"],
    thresholds: {},
    brief:
      "日柱与其他柱位干支完全相同，提示自我位置与对应柱位之间存在重复回响，需要结合全局复核。",
    reasoning: [
      "由 pillar_stem 与 pillar_branch 重建四柱。",
      "日柱与年、月、时任一柱的天干和地支同时相同。",
    ],
  },
  {
    id: "spouse_palace_relation_tension",
    version: "natal-composition-rule-v1",
    title: "日支关系牵动",
    role: "tension",
    status: "derived",
    importance: "medium",
    baseConfidence: "medium",
    priority: 76,
    tags: ["日支", "关系", "张力", "复核"],
    domains: ["spouse", "self"],
    thresholds: {
      tensionRelationTypes: [
        "branch_clash",
        "branch_punish",
        "branch_self_punish",
        "branch_harm",
        "branch_break",
        "刑",
        "冲",
        "害",
        "破",
      ],
    },
    brief:
      "日支参与刑、冲、害、破类关系，提示关系宫位被牵动，可作为关系互动与边界议题的复核点。",
    reasoning: [
      "relation.has_relation 中存在 day branch 参与者。",
      "relationType 属于刑、冲、害、破的张力关系集合。",
    ],
  },
  {
    id: "peer_wealth_competition",
    version: "natal-composition-rule-v1",
    title: "比劫牵财",
    role: "tension",
    status: "conditional",
    importance: "medium",
    baseConfidence: "medium",
    priority: 70,
    tags: ["比劫", "财星", "资源", "边界"],
    domains: ["wealth", "friends", "siblings", "self"],
    thresholds: {
      peerMinWeightedCount: 1,
      wealthMinWeightedCount: 0.5,
    },
    brief:
      "比劫与财星均有实际权重，提示资源、合作、分配和边界之间存在互动线索。",
    reasoning: [
      "合同口径仅累计比肩与劫财，不包含日主自身；peer weightedCount 达到1，等价于旧口径 groupCounts.peer 达到2。",
      "正财或偏财 weightedCount 达到0.5，说明财星存在实际落点。",
    ],
  },
  {
    id: "resource_heavy_output_weak",
    version: "natal-composition-rule-v1",
    title: "印重食伤弱",
    role: "tension",
    status: "conditional",
    importance: "medium",
    baseConfidence: "medium",
    priority: 68,
    tags: ["印星", "食伤", "表达", "条件"],
    domains: ["self", "career", "children", "fortune"],
    thresholds: {
      resourceMinWeightedCount: 2,
      outputWeakMaxWeightedCount: 0.7,
      resourceToOutputRatioMin: 0,
    },
    brief:
      "印星权重明显高于食伤组，提示吸收、资质与表达输出之间存在条件差异，需要结合通关和现实应象复核。",
    reasoning: [
      "印星组 weightedCount 达到规则阈值。",
      "食伤组 weightedCount 处于较弱阈值内；比例计算保留为复核信息，本版不作为额外必要条件。",
    ],
  },
  {
    id: "element_bias_visible",
    version: "natal-composition-rule-v1",
    title: "五行偏性明显",
    role: "tension",
    status: "derived",
    importance: "medium",
    baseConfidence: "medium",
    priority: 66,
    tags: ["五行", "偏性", "复核"],
    domains: ["self", "health", "fortune"],
    thresholds: {
      acceptedBiasLevels: ["偏颇", "明显偏颇", "偏枯"],
      requireDominantElements: true,
      requireWeakestElements: true,
    },
    brief:
      "五行偏性、偏旺元素与偏弱元素同时可见，提示结构分布不均，需要结合调候和通关条件复核。",
    reasoning: [
      "bias_level、dominant_elements、weakest_elements 三类事实同时命中。",
      "该规则只记录五行分布形态，不直接对应具体疾病。",
    ],
  },
  {
    id: "month_command_official",
    version: "natal-composition-rule-v1",
    title: "月令官星",
    role: "support",
    status: "derived",
    importance: "high",
    baseConfidence: "high",
    priority: 82,
    tags: ["月令", "官杀", "主轴"],
    domains: ["career", "self"],
    thresholds: {
      acceptedTenGods: ["正官", "七杀"],
    },
    brief:
      "月支主气为官杀，提示规则、责任或约束议题进入月令主轴，需要结合日主承载与印比财食配置复核。",
    reasoning: [
      "month 的 pillar_branch_main_ten_god 为正官或七杀。",
      "该规则只记录月令主气结构，不单凭月令判断事业结果。",
    ],
    titleByTenGod: {
      正官: "月令正官",
      七杀: "月令七杀",
    },
  },
  {
    id: "output_wealth_chain",
    version: "natal-composition-rule-v1",
    title: "食伤生财线索",
    role: "core",
    status: "derived",
    importance: "high",
    baseConfidence: "high",
    priority: 90,
    tags: ["食伤", "财星", "项目", "变现"],
    domains: ["career", "wealth", "children"],
    thresholds: {
      outputMinWeightedCount: 0.9,
      wealthMinWeightedCount: 0.5,
    },
    brief:
      "表达、技术、作品或项目成果与现实收益之间存在可复核的转化通道。",
    reasoning: [
      "食伤组 weightedCount 达到0.9，说明输出端有实际落点。",
      "财星组 weightedCount 达到0.5，说明现实资源或收益端有承接位置。",
      "合同 ten_god_presence 的组权重与旧 groupCounts 同标尺，本规则阈值可直接迁移。",
    ],
  },
  {
    id: "hurting_officer_resource_balance",
    version: "natal-composition-rule-v1",
    title: "伤官配印线索",
    role: "core",
    status: "conditional",
    importance: "medium",
    baseConfidence: "medium",
    priority: 88,
    tags: ["伤官", "印星", "表达", "体系"],
    domains: ["self", "career", "fortune", "children"],
    thresholds: {
      hurtingOfficerMinWeightedCount: 0.6,
      resourceMinWeightedCount: 0.7,
    },
    brief:
      "表达、批判或创造力与学习、资质、专业体系之间存在整理和承接线索。",
    reasoning: [
      "伤官 weightedCount 达到0.6，说明表达与判断端有实际落点。",
      "印星组 weightedCount 达到0.7，说明体系、学习或资质端有实际落点。",
      "单十神与十神组 weightedCount 均沿用旧十神加权口径。",
    ],
  },
  {
    id: "hurting_officer_meets_officer",
    version: "natal-composition-rule-v1",
    title: "伤官见官线索",
    role: "tension",
    status: "conditional",
    importance: "medium",
    baseConfidence: "medium",
    priority: 91,
    tags: ["伤官", "正官", "规则", "表达"],
    domains: ["career", "self", "spouse", "friends"],
    thresholds: {
      hurtingOfficerMinWeightedCount: 0.6,
      properOfficerMinWeightedCount: 0.6,
    },
    brief:
      "个人表达、判断和自由度容易与规则、岗位要求或权威体系形成拉扯。",
    reasoning: [
      "伤官 weightedCount 达到0.6。",
      "正官 weightedCount 达到0.6。",
      "合同 ten_god_presence 与旧 weightedCounts 同标尺，不额外放宽或收紧。",
    ],
  },
  {
    id: "wealth_heavy_body_weak",
    version: "natal-composition-rule-v1",
    title: "财多身弱线索",
    role: "tension",
    status: "conditional",
    importance: "high",
    baseConfidence: "medium",
    priority: 93,
    tags: ["财星", "日主", "承载", "压力"],
    domains: ["wealth", "spouse", "self", "health"],
    thresholds: {
      wealthMinWeightedCount: 1.8,
      maxDayMasterStrengthScore: 45,
    },
    brief:
      "现实资源、金钱责任或关系责任较多，而日主承接分偏低时，压力和消耗线索需要重点复核。",
    reasoning: [
      "财星组 weightedCount 达到1.8，说明财星分量偏重。",
      "day_master.strength_score 小于等于45，说明日主承接分偏弱。",
      "财星组权重与旧 groupCounts 同标尺，strength_score 与旧日主强弱分同为0到100分口径。",
    ],
  },
  {
    id: "officer_killing_mixed",
    version: "natal-composition-rule-v1",
    title: "官杀混杂线索",
    role: "tension",
    status: "conditional",
    importance: "medium",
    baseConfidence: "medium",
    priority: 84,
    tags: ["正官", "七杀", "规则", "主次"],
    domains: ["career", "self", "spouse", "health"],
    thresholds: {
      properOfficerMinWeightedCount: 0.5,
      killingMinWeightedCount: 0.5,
    },
    brief:
      "稳定规则与高压约束同时有落点，容易出现多套标准、职责边界或主次关系需要复核。",
    reasoning: [
      "正官 weightedCount 达到0.5。",
      "七杀 weightedCount 达到0.5。",
      "正官与七杀均读取 contract ten_god_presence，和旧 weightedCounts 同标尺。",
    ],
  },
  {
    id: "day_branch_combined",
    version: "natal-composition-rule-v1",
    title: "日支逢合",
    role: "support",
    status: "derived",
    importance: "medium",
    baseConfidence: "high",
    priority: 84,
    tags: ["日支", "夫妻宫", "合", "连接"],
    domains: ["spouse", "self", "friends"],
    thresholds: {
      combineRelationTypes: [
        "branch_combine",
        "three_harmony",
        "three_meeting",
        "half_harmony",
        "arch_harmony",
        "合",
        "六合",
        "三合",
        "三会",
        "半合",
        "拱合",
      ],
    },
    brief:
      "日支与其他柱形成合类连接，提示关系宫位存在牵连、合作或绑定线索。",
    reasoning: [
      "relation.has_relation 中存在 day branch 参与者。",
      "relationType 属于六合、三合、三会、半合或拱合等合类关系。",
      "合只表示连接和牵绊，不直接判断关系结果。",
    ],
  },
  {
    id: "metal_water_fire_weak",
    version: "natal-composition-rule-v1",
    title: "金水偏重、火气不足线索",
    role: "conditional",
    status: "conditional",
    importance: "medium",
    baseConfidence: "medium",
    priority: 75,
    tags: ["金水", "火弱", "寒暖", "调候"],
    domains: ["health", "self", "fortune", "career"],
    thresholds: {
      metalMinCount: 1.5,
      waterMinCount: 1.5,
      fireMaxCount: 0.5,
    },
    brief:
      "金水分量较重而火气偏弱时，结构容易呈现冷静、慢热或推动力需补充的复核方向。",
    reasoning: [
      "element_count 中金达到1.5。",
      "element_count 中水达到1.5。",
      "element_count 中火小于等于0.5。",
      "新版 element_count 与旧 elements.counts 同为五行数量口径；本规则不直接对应具体疾病。",
    ],
  },
];
