export const combinationRules = [
  {
    id: "peer_heavy_wealth_weak",
    label: "比劫重而财星不显",
    when: { includesAny: ["比劫重", "比肩", "劫财"], excludesStrong: ["财星强", "财星透出明显", "财星明显"] },
    domains: ["wealth", "siblings", "friends"],
    weight: 8,
    judgement: "比劫重而财星不显时，财务上不是完全没机会，而是钱财容易被人情、合作、同辈关系分走。",
    manifestation: "常见合伙分利、朋友花费、资源被分摊，或者钱来之后不容易完全留在自己手里。",
    pressure: "不能直接断贫，要看食伤是否能生财、大运是否把财星引出来。",
    keywords: ["资源分流", "合伙分利", "钱财不易独聚"],
    evidenceText: "比劫代表同类、竞争和分夺，财星代表现实资源；两者组合时，要看资源是否被同辈和合作关系牵动。",
  },
  {
    id: "peer_heavy_wealth_visible",
    label: "比劫重而财星有迹",
    when: { includesAny: ["比劫重", "财星有迹", "财星明显"] },
    domains: ["wealth", "siblings", "friends"],
    weight: 7,
    judgement: "比劫与财星同时有迹，钱财和同辈合作、人情资源容易绑在一起。",
    manifestation: "容易出现共同做事、资源共享、收益分配、朋友合作带财也带压力的情况。",
    pressure: "财星是否能留住，要看食伤承接、规则约束和岁运是否让财星成形。",
    keywords: ["合作带财", "收益分配", "人情资源"],
    evidenceText: "财星给资源入口，比劫带同辈与分配，两者同现时财务更容易牵动合作关系。",
  },
  {
    id: "resource_visible_output_weak",
    label: "印星明显而食伤弱",
    when: { includesAny: ["印星明显", "印星透", "正印", "偏印"], excludesStrong: ["食伤明显", "食神", "伤官"] },
    domains: ["self", "career", "fortune", "children"],
    weight: 7,
    judgement: "印星明显而食伤弱，吸收、学习、资质和安全感较重，外放表达不算最顺。",
    manifestation: "容易重资料、证照、体系和保护感，做成果时更偏稳扎稳打。",
    pressure: "如果后天运势引出食伤，表达和作品层会比原局更活。",
    keywords: ["学习吸收", "体系感", "表达偏慢"],
    evidenceText: "印星主学习、保护和吸收，食伤主表达、输出和作品；印重食伤弱时，内化强于外放。",
  },
  {
    id: "resource_visible_output_visible",
    label: "印星明显而食伤明显",
    when: { includesAny: ["印星明显", "食伤明显", "食神", "伤官"] },
    domains: ["career", "children", "fortune", "self"],
    weight: 8,
    judgement: "印星与食伤都有力，学习吸收和表达输出之间有转化空间。",
    manifestation: "容易把资料、经验、专业训练转成作品、表达、项目或可交付成果。",
    pressure: "若关系冲动或官杀压力重，输出节奏会被规则和责任拉住。",
    keywords: ["学以致用", "表达输出", "作品成果"],
    evidenceText: "印星提供知识与保护，食伤提供表达与结果，两者同现时更容易形成能力转化。",
  },
  {
    id: "officer_visible_resource_support",
    label: "官杀明显而印星承接",
    when: { includesAny: ["官杀明显", "正官", "七杀", "印星明显", "正印", "偏印"] },
    domains: ["career", "parents", "fortune", "self"],
    weight: 8,
    judgement: "官杀有压力，印星能承接时，责任、规则、岗位压力容易转成资质和身份。",
    manifestation: "事业上更容易走制度、证照、专业身份、规则体系或被要求承担责任的路径。",
    pressure: "印星承接不足时，官杀更像压力；承接得住时，压力更容易变成位置感。",
    keywords: ["规则承接", "岗位身份", "资质压力"],
    evidenceText: "官杀主规则、责任和压力，印星主承接、保护和资质，两者相连时看压力能否被转化。",
  },
  {
    id: "officer_visible_hurting_visible",
    label: "官杀明显而伤官明显",
    when: { includesAny: ["官杀明显", "伤官", "食伤明显"] },
    domains: ["career", "spouse", "self"],
    weight: 7,
    judgement: "官杀与伤官同见，事业和关系里容易有规则压力与表达反弹并存。",
    manifestation: "容易遇到制度、上级、考核和个人表达之间的摩擦，也可能体现为技术输出挑战规则。",
    pressure: "若印星能调和，反弹感会转成专业表达；若无承接，容易显得较硬。",
    keywords: ["规则摩擦", "表达反弹", "技术挑战"],
    evidenceText: "官杀代表规则压力，伤官代表表达与突破，两者同现时要看是否有印星或财星转化。",
  },
  {
    id: "wealth_visible_peer_visible",
    label: "财星明显而比劫明显",
    when: { includesAny: ["财星明显", "财星有迹", "比劫明显", "比劫重"] },
    domains: ["wealth", "friends", "siblings"],
    weight: 8,
    judgement: "财星和比劫同时明显，财富不只是收入问题，也牵动分配、人情和合作边界。",
    manifestation: "容易一边有资源入口，一边有人情支出、合作分利或同辈竞争。",
    pressure: "财能不能聚，要看规则、食伤转化和阶段运势是否帮忙收束。",
    keywords: ["财务分配", "人情支出", "合作边界"],
    evidenceText: "财星为资源，比劫为同类分配，二者同现时财务常与人际边界相连。",
  },
  {
    id: "output_visible_wealth_trace",
    label: "食伤明显而财星有迹",
    when: { includesAny: ["食伤明显", "食神", "伤官", "财星有迹", "财星明显"] },
    domains: ["wealth", "career", "children"],
    weight: 8,
    judgement: "食伤明显而财星有迹，能力输出、项目作品和钱财转化之间有连接。",
    manifestation: "更容易靠技能、表达、项目、内容、交付成果或专业服务带来收益入口。",
    pressure: "财务稳定度还要看财星根气、日主承载和合作分配。",
    keywords: ["技能变现", "项目收益", "作品转化"],
    evidenceText: "食伤为输出，财星为资源收益，食伤生财是能力转成现实收益的经典入口。",
  },
  {
    id: "output_visible_officer_pressure",
    label: "食伤明显而官杀有压力",
    when: { includesAny: ["食伤明显", "食神", "伤官", "官杀明显", "正官", "七杀"] },
    domains: ["career", "self", "children"],
    weight: 7,
    judgement: "食伤和官杀同时有力，输出能力与规则压力并存。",
    manifestation: "容易在工作里既要交付成果，又要面对流程、审核、责任和外部评价。",
    pressure: "若印星或财星能转化，压力会变成专业路径；否则容易有被管束感。",
    keywords: ["输出承压", "流程考核", "专业交付"],
    evidenceText: "食伤主表达和成果，官杀主规则和压力，同见时看输出如何被制度接住。",
  },
  {
    id: "day_branch_clashed",
    label: "日支被冲",
    when: { includesAny: ["日支被冲", "日柱", "地支六冲", "天克地冲"] },
    domains: ["spouse", "self", "movement"],
    weight: 9,
    judgement: "日支被冲时，亲密关系、自身安定感和生活环境更容易出现被外部牵动的感觉。",
    manifestation: "容易体现为关系沟通反复、空间变化、节奏调整，或者内在安全感被现实事务推动。",
    pressure: "冲不等于坏事，轻重看月令、柱位、透干和岁运是否再触发。",
    keywords: ["关系牵动", "安全感波动", "环境变化"],
    evidenceText: "日支为关系宫与自身坐下位置，被冲时先看关系、安全感和居住环境的动象。",
  },
  {
    id: "day_branch_combined",
    label: "日支被合",
    when: { includesAny: ["日支被合", "日柱", "地支六合", "天干五合"] },
    domains: ["spouse", "friends", "wealth"],
    weight: 7,
    judgement: "日支被合时，关系容易带有绑定、牵连、合作和互相影响的色彩。",
    manifestation: "感情、人情、合作资源容易交织在一起，关系推进常伴随现实责任。",
    pressure: "合能不能化，要看月令、透干、根气和现实关系结构。",
    keywords: ["关系绑定", "合作牵连", "现实责任"],
    evidenceText: "合象主牵连、绑定和合作，落在日支时优先看关系模式。",
  },
  {
    id: "day_branch_punished_harmed_broken",
    label: "日支被刑害破",
    when: { includesAny: ["日支被刑", "日支被害", "日支被破", "地支三刑", "地支六害", "地支六破", "地支穿"] },
    domains: ["spouse", "self", "health"],
    weight: 8,
    judgement: "日支见刑害破时，关系和自身状态容易有细碎摩擦、暗耗或边界压力。",
    manifestation: "更像沟通里的不顺、关系里的小反复、情绪体感的内耗，而不是单一事件。",
    pressure: "刑害破要看具体柱位和强弱，不能放大成固定结论。",
    keywords: ["细碎摩擦", "边界压力", "暗耗感"],
    evidenceText: "刑害破偏细碎牵动，落到日支时常从关系宫和自身坐下状态取象。",
  },
  {
    id: "year_month_relations",
    label: "年月被冲合刑害",
    when: { includesAny: ["年柱", "月柱", "年月", "地支六冲", "地支六合", "地支三刑", "地支六害", "地支六破"] },
    domains: ["parents", "property", "career"],
    weight: 6,
    judgement: "年月被关系牵动，早年家庭、父母秩序和成长环境容易带出变化感。",
    manifestation: "家中规则、父母分工、居住环境或早期资源可能不是完全平直的一条线。",
    pressure: "若关系没有落到年月，不要把家庭线索放大。",
    keywords: ["早年变化", "家庭秩序", "成长环境"],
    evidenceText: "年柱看外部背景，月柱看成长环境，年月受关系牵动时家庭和早年资源更有存在感。",
  },
  {
    id: "hour_output_visible",
    label: "时柱食伤明显",
    when: { includesAny: ["时柱", "食神", "伤官", "食伤明显"] },
    domains: ["children", "career", "fortune"],
    weight: 7,
    judgement: "时柱食伤明显，子女结果、作品成果和后续落地能力更容易有表现。",
    manifestation: "想法更容易通过项目、技能、表达、作品或长期规划变成可见结果。",
    pressure: "结果是否稳定，要看食伤是否被冲、是否能接财或接事业。",
    keywords: ["作品成果", "后续落地", "输出能力"],
    evidenceText: "时柱看后续结果层，食伤看输出表达，二者同现时更看重成果落地。",
  },
  {
    id: "hour_clashed",
    label: "时柱被冲",
    when: { includesAny: ["时柱被冲", "时柱", "地支六冲", "天克地冲"] },
    domains: ["children", "movement", "property"],
    weight: 7,
    judgement: "时柱被冲时，后续规划、子女结果、居住或执行层容易有变动感。",
    manifestation: "项目后段、生活远景、子女结果或住处节奏容易出现调整和转换。",
    pressure: "时柱动象落地与否，要看岁运是否再引动。",
    keywords: ["后续变化", "执行调整", "结果层动象"],
    evidenceText: "时柱为后续结果与远景位置，被冲时多看结果层和生活环境的变化。",
  },
  {
    id: "earth_visible_wealth_resource_trace",
    label: "土气明显而财印有迹",
    when: { includesAny: ["土气明显", "土", "财星有迹", "印星明显"] },
    domains: ["property", "wealth", "parents"],
    weight: 7,
    judgement: "土气明显且财印有迹，固定承载、家庭资源和资产承接有观察点。",
    manifestation: "更容易围绕房产、居住、稳定资产、家庭资源或长期积累形成现实议题。",
    pressure: "土重也可能带来滞重感，要看流通和冲动关系。",
    keywords: ["固定承载", "家庭资产", "稳定积累"],
    evidenceText: "土主承载和稳定，财印分别对应资源与保护，组合后可看田宅资产和家庭承接。",
  },
  {
    id: "water_visible_cold_damp",
    label: "水气明显而寒湿感较重",
    when: { includesAny: ["水气明显", "水", "寒湿感", "寒暖燥湿"] },
    domains: ["health", "fortune", "movement"],
    weight: 6,
    judgement: "水气与寒湿感较重时，人的状态更偏流动、敏感、信息感和体感湿冷。",
    manifestation: "容易体现为思绪流动、环境适应、睡眠节奏、寒湿体感或对安全感的需求。",
    pressure: "若火土能承接，水气会转成信息和适应力。",
    keywords: ["寒湿体感", "信息流动", "安全感"],
    evidenceText: "水主流动和信息，寒湿偏性落到体质与精神层时，更多看长期体感和心态。",
  },
  {
    id: "fire_weak_or_restrained",
    label: "火弱或火受制",
    when: { includesAny: ["火弱", "火受制", "火气不显"] },
    domains: ["health", "fortune", "career"],
    weight: 6,
    judgement: "火弱或受制时，热度、表达、反馈感和外放动力不算最顺。",
    manifestation: "容易表现为启动慢、热情需要环境带动，或者更重稳定和安全感。",
    pressure: "若食伤或岁运带火，表达与行动热度会被带出来。",
    keywords: ["热度不足", "表达偏慢", "反馈感"],
    evidenceText: "火主热度、表达和反馈，偏弱或受制时要看后天是否补出行动感。",
  },
  {
    id: "element_flow_good",
    label: "五行流通较好",
    when: { includesAny: ["五行流通较好", "五行流通", "流通"] },
    domains: ["self", "career", "fortune", "health"],
    weight: 7,
    judgement: "五行流通较好时，人的适应、转化和把事情串起来的能力更有空间。",
    manifestation: "容易在学习、工作、关系和生活节奏之间形成转换，不容易卡在单一象上。",
    pressure: "流通好也要看主线强弱，不能因此忽略具体压力点。",
    keywords: ["适应转化", "结构流动", "承接力"],
    evidenceText: "五行流通说明气机有转化路径，落到现实中多看适应与承接。",
  },
  {
    id: "element_bias_clear",
    label: "五行偏颇明显",
    when: { includesAny: ["五行偏颇明显", "五行偏颇", "偏重", "过旺", "过弱"] },
    domains: ["health", "self", "fortune"],
    weight: 7,
    judgement: "五行偏颇明显时，性格、体质和长期心态容易围绕某一类气象反复呈现。",
    manifestation: "会在做事偏好、身体体感、情绪反应或生活节奏里形成比较固定的倾向。",
    pressure: "偏颇不等于问题，关键看有没有通关、调候和岁运补偏。",
    keywords: ["五行偏性", "体质倾向", "长期重复"],
    evidenceText: "五行偏颇是结构倾向，重点看偏性如何落到性格、体质和生活节奏。",
  },
];
