export const domainRules = [
  {
    key: "self",
    label: "命主自身",
    aliases: ["本人", "性格", "自我", "命主"],
    primarySignals: ["日主", "日主五行", "日柱", "月令", "强弱", "比劫", "印星", "personality", "life_pattern"],
    secondarySignals: ["五行主导", "通根", "透干", "边界", "自我意识"],
    relatedPillars: ["日柱", "月柱"],
    relatedTopics: ["personality", "life_pattern"],
    watchRelations: ["冲", "合", "刑", "害", "破"],
    positiveImages: ["性格底色", "自我意识", "做事节奏", "边界感", "反应方式", "稳定性"],
    pressureImages: ["自我拉扯", "不易妥协", "节奏被牵动", "边界感受压"],
    weakEvidenceText: "命主自身这条线不是最重的外显主题，更多体现为日主底色和月令环境的基础气质。",
    defaultJudgement: "命主自身要看日主、月令、强弱和五行主导，核心是这个人的性格底色与做事节奏。",
  },
  {
    key: "parents",
    label: "父母家庭",
    aliases: ["父母", "家庭", "早年", "家里"],
    primarySignals: ["年柱", "月柱", "印星", "财星", "family"],
    secondarySignals: ["年月关系", "家庭规则", "早年资源", "成长环境"],
    relatedPillars: ["年柱", "月柱"],
    relatedTopics: ["family"],
    watchRelations: ["冲", "合", "刑", "害", "破"],
    positiveImages: ["父母背景", "早年环境", "家庭秩序", "家中规则", "成长资源"],
    pressureImages: ["成长压力", "家庭牵连", "早年不稳", "父母分工压力"],
    weakEvidenceText: "父母家庭不是原局最突出的主线，早年影响更多从年柱月柱和印财位置作基础判断。",
    defaultJudgement: "父母家庭要看年柱月柱、印星财星和年月关系，重点是早年环境与家中秩序。",
  },
  {
    key: "siblings",
    label: "兄弟同辈",
    aliases: ["兄弟", "姐妹", "同辈", "同龄"],
    primarySignals: ["比肩", "劫财", "比劫", "比劫重", "同辈", "竞争"],
    secondarySignals: ["月柱", "合作", "资源分配", "合伙边界"],
    relatedPillars: ["月柱", "日柱"],
    relatedTopics: ["personality", "relationship"],
    watchRelations: ["合", "冲", "刑", "害", "破"],
    positiveImages: ["同辈助力", "合作分工", "行动同盟", "朋友同类"],
    pressureImages: ["同辈竞争", "资源分配", "合伙边界", "分利压力"],
    weakEvidenceText: "兄弟同辈线索不算强，更多作为朋友同龄、竞争合作和资源边界的辅助观察。",
    defaultJudgement: "兄弟同辈要看比肩劫财和比劫统计，重点是同龄关系、合作竞争与资源分配。",
  },
  {
    key: "spouse",
    label: "夫妻感情",
    aliases: ["感情", "婚恋", "夫妻", "亲密关系"],
    primarySignals: ["日支", "日柱", "配偶宫", "财星", "官杀", "relationship"],
    secondarySignals: ["日支被冲", "日支被合", "日支被刑害破", "边界", "安全感"],
    relatedPillars: ["日柱"],
    relatedTopics: ["relationship"],
    watchRelations: ["冲", "合", "刑", "害", "破"],
    positiveImages: ["感情模式", "亲密关系", "安全感", "沟通方式", "现实责任"],
    pressureImages: ["关系牵连", "边界拉扯", "沟通反复", "责任分配压力"],
    weakEvidenceText: "夫妻感情不是原局最重的主题，先以日支关系宫作为基本入口。",
    defaultJudgement: "夫妻感情要看日支、日柱、配偶宫关系和财官取象，重点是关系模式与安全感。",
  },
  {
    key: "children",
    label: "子女结果",
    aliases: ["子女", "结果", "作品", "后续"],
    primarySignals: ["时柱", "食神", "伤官", "食伤", "输出", "作品"],
    secondarySignals: ["项目结果", "晚期规划", "时支关系", "study_skill", "life_pattern"],
    relatedPillars: ["时柱"],
    relatedTopics: ["study_skill", "life_pattern"],
    watchRelations: ["冲", "合", "刑", "害", "破"],
    positiveImages: ["输出能力", "作品成果", "项目结果", "长期规划", "后续落地"],
    pressureImages: ["结果反复", "输出受阻", "规划延迟", "时柱被动"],
    weakEvidenceText: "子女结果层不是原局最重的主题，更多要等阶段事务把时柱或食伤引出来。",
    defaultJudgement: "子女结果不看数量，重点看时柱、食伤、作品成果和长期规划。",
  },
  {
    key: "wealth",
    label: "财帛财富",
    aliases: ["财运", "财富方式", "钱财", "资源"],
    primarySignals: ["正财", "偏财", "财星", "财星明显", "财星有迹", "食伤生财", "财星透出", "wealth"],
    secondarySignals: ["比劫", "食神", "伤官", "土", "交易", "资源调度", "比劫夺财"],
    relatedPillars: ["日柱", "月柱"],
    relatedTopics: ["wealth"],
    watchRelations: ["冲", "合", "刑", "害", "破"],
    positiveImages: ["收入意识", "资源调度", "交易能力", "现实收益", "资产承接"],
    pressureImages: ["花费压力", "资源分流", "合伙分利", "钱财不易独聚"],
    weakEvidenceText: "财帛不是原局最突出的主线，财富方式更多要等大运流年把财星或食伤引出来后再看。",
    defaultJudgement: "财帛财富要看财星、食伤转化和日主承载力，不能只看有没有财星。",
  },
  {
    key: "health",
    label: "疾厄健康",
    aliases: ["健康", "体质", "疾厄", "身体"],
    primarySignals: ["五行偏颇", "寒暖燥湿", "日主强弱", "health"],
    secondarySignals: ["水", "火", "土", "金", "木", "失衡", "压力反应"],
    relatedPillars: ["日柱", "月柱"],
    relatedTopics: ["health"],
    watchRelations: ["冲", "刑", "害", "破"],
    positiveImages: ["体质取象", "睡眠", "消化", "皮肤", "呼吸", "循环", "压力反应"],
    pressureImages: ["寒湿燥热偏性", "五行偏颇", "长期疲惫", "作息承载压力"],
    weakEvidenceText: "疾厄健康只作体质倾向，不作医学诊断；原局证据不重时以生活习惯为辅助参考。",
    defaultJudgement: "疾厄健康看五行偏颇、寒暖燥湿和日主承载，落点是体质取象与压力反应。",
  },
  {
    key: "movement",
    label: "迁移环境",
    aliases: ["迁移", "搬迁", "出行", "异地"],
    primarySignals: ["冲", "驿马", "寅", "申", "巳", "亥", "movement"],
    secondarySignals: ["地支关系", "水木流动", "环境变化", "通勤", "岗位环境"],
    relatedPillars: ["年柱", "日柱", "时柱"],
    relatedTopics: ["movement"],
    watchRelations: ["冲", "破", "反吟", "天克地冲"],
    positiveImages: ["搬迁", "出行", "异地", "通勤", "环境变化", "岗位切换"],
    pressureImages: ["环境不稳", "奔波感", "节奏切换", "外部牵动"],
    weakEvidenceText: "迁移环境不是原局最突出的主线，更多等岁运冲动或现实计划引动后才明显。",
    defaultJudgement: "迁移环境看冲动关系、驿马动象和地支流动，重点是空间变化与环境切换。",
  },
  {
    key: "friends",
    label: "交友人脉",
    aliases: ["朋友", "人脉", "圈层", "合作资源"],
    primarySignals: ["比劫", "劫财", "合", "同辈关系", "relationship"],
    secondarySignals: ["合作资源", "朋友圈", "人情往来", "资源边界"],
    relatedPillars: ["月柱", "日柱"],
    relatedTopics: ["relationship", "personality"],
    watchRelations: ["合", "冲", "刑", "害", "破"],
    positiveImages: ["朋友圈", "人脉", "合作", "合伙", "资源交换"],
    pressureImages: ["竞争", "资源边界", "人情牵连", "合伙分利"],
    weakEvidenceText: "交友人脉不是原局最突出的主线，外部圈层更多要看后天环境和岁运牵动。",
    defaultJudgement: "交友人脉看比劫、合象和合作资源，重点是外部朋友、人情往来与资源边界。",
  },
  {
    key: "career",
    label: "官禄事业",
    aliases: ["事业", "工作", "官禄", "职业"],
    primarySignals: ["官杀", "正官", "七杀", "食伤", "印星", "career"],
    secondarySignals: ["月柱", "月令", "岗位规则", "事业方向", "技术输出"],
    relatedPillars: ["月柱", "日柱", "时柱"],
    relatedTopics: ["career", "study_skill"],
    watchRelations: ["冲", "合", "刑", "害", "破"],
    positiveImages: ["职业方向", "岗位身份", "规则压力", "技术输出", "管理", "考核"],
    pressureImages: ["职责压力", "考核压力", "规则冲突", "输出受制"],
    weakEvidenceText: "官禄事业不是原局最突出的主线，事业落点更多要看后天行业和岁运承接。",
    defaultJudgement: "官禄事业看官杀、食伤、印星、月柱月令，重点是职业方向和岗位承压方式。",
  },
  {
    key: "property",
    label: "田宅资产",
    aliases: ["田宅", "房产", "固定资产", "居住"],
    primarySignals: ["土", "财星", "印星", "辰", "戌", "丑", "未", "固定资产"],
    secondarySignals: ["年柱", "月柱", "居住环境", "wealth", "family"],
    relatedPillars: ["年柱", "月柱", "日柱"],
    relatedTopics: ["wealth", "family"],
    watchRelations: ["冲", "合", "刑", "害", "破"],
    positiveImages: ["房产", "固定资产", "居住环境", "家庭资产", "土地不动产", "稳定承载"],
    pressureImages: ["居住变化", "资产承载压力", "家庭资产牵连", "动土变化"],
    weakEvidenceText: "田宅资产取象证据不强，先看家庭背景、财星承接和土气稳定度。",
    defaultJudgement: "田宅资产看土气、财星、印星和年柱月柱，重点是固定承载与居住资产。",
  },
  {
    key: "fortune",
    label: "福德精神",
    aliases: ["福德", "精神", "心态", "兴趣"],
    primarySignals: ["印星", "食伤", "五行流通", "寒暖", "life_pattern", "personality"],
    secondarySignals: ["health", "精神安全感", "兴趣系统", "内耗", "舒适度"],
    relatedPillars: ["日柱", "时柱"],
    relatedTopics: ["life_pattern", "personality", "health"],
    watchRelations: ["冲", "合", "刑", "害", "破"],
    positiveImages: ["精神安全感", "长期心态", "兴趣系统", "享受能力", "信念系统", "舒适度"],
    pressureImages: ["内耗", "孤独感", "不易放松", "精神承接压力"],
    weakEvidenceText: "福德精神不是原局最外显的主线，更多从印星、食伤和五行流通看长期心态。",
    defaultJudgement: "福德精神看印星、食伤、五行流通和寒暖状态，落点是精神安全感与长期心态。",
  },
];
