const groupLabels = {
  peer: "比劫",
  resource: "印星",
  output: "食伤",
  wealth: "财星",
  officer: "官杀",
};

export const atomicNatalRules = [
  {
    id: "day_master_profile",
    domains: ["self", "fortune"],
    category: "day_master",
    role: "base",
    match: (fv) => Boolean(fv.dayMaster?.stem),
    score: (fv) => 55 + Number(fv.dayMaster?.strengthScore ?? 0) / 4,
    buildFact: (fv) => fact({
      id: "day_master_profile",
      label: dayMasterLabel(fv),
      meaning: `${fv.dayMaster?.element || "日主"}为自身底色，强弱为${fv.dayMaster?.strengthLevel || "待复核"}`,
      score: 62,
      domains: ["self", "fortune"],
      category: "day_master",
      evidence: [`日主为${fv.dayMaster?.label || fv.dayMaster?.stem}`, `强弱初判为${fv.dayMaster?.strengthLevel || "待复核"}`],
      tags: ["日主", fv.dayMaster?.element, fv.dayMaster?.strengthLevel],
    }),
  },
  ...["resource", "peer", "output", "wealth", "officer"].map((group) => ({
    id: `${group}_dominant`,
    domains: groupDomains(group),
    category: "ten_god",
    role: group === "peer" ? "support" : "main",
    match: (fv) => Number(fv.tenGods?.groupCounts?.[group] ?? 0) >= 3,
    score: (fv) => 62 + Number(fv.tenGods?.groupCounts?.[group] ?? 0) * 5,
    buildFact: (fv) => fact({
      id: `${group}_dominant`,
      label: `${groupLabels[group]}明显`,
      meaning: groupMeaning(group),
      score: 62 + Number(fv.tenGods?.groupCounts?.[group] ?? 0) * 5,
      domains: groupDomains(group),
      category: "ten_god",
      evidence: [`${groupLabels[group]}统计约${fv.tenGods?.groupCounts?.[group] ?? 0}`],
      tags: [groupLabels[group], "十神"],
    }),
  })),
  {
    id: "resource_visible_month_stem",
    domains: ["self", "parents", "career", "fortune"],
    category: "ten_god",
    role: "support",
    match: (fv) => /印/.test(fv.pillars?.month?.stemTenGod || ""),
    score: () => 82,
    buildFact: (fv) => fact({
      id: "resource_visible_month_stem",
      label: "印星透月干",
      meaning: "学习吸收、经验承接和系统意识较有存在感",
      score: 82,
      domains: ["self", "parents", "career", "fortune"],
      category: "ten_god",
      specificity: "high",
      evidence: [`月干见${fv.pillars?.month?.stemTenGod}`, "月柱为成长和事业环境位置"],
      tags: ["印星", "月干", "学习吸收"],
    }),
  },
  {
    id: "peer_visible_hour_stem",
    domains: ["self", "siblings", "friends"],
    category: "ten_god",
    role: "support",
    match: (fv) => /比肩|劫财/.test(fv.pillars?.hour?.stemTenGod || ""),
    score: () => 72,
    buildFact: (fv) => fact({
      id: "peer_visible_hour_stem",
      label: "比劫透时干",
      meaning: "自我节奏、同辈关系和后续分工较有存在感",
      score: 72,
      domains: ["self", "siblings", "friends"],
      category: "ten_god",
      specificity: "high",
      evidence: [`时干见${fv.pillars?.hour?.stemTenGod}`, "时柱为后续结果和晚近表现位置"],
      tags: ["比劫", "自我节奏", "同辈"],
    }),
  },
  {
    id: "wealth_visible_year_month",
    domains: ["wealth", "parents", "property"],
    category: "ten_god",
    role: "resource",
    match: (fv) => /财/.test([fv.pillars?.year?.stemTenGod, fv.pillars?.year?.branchMainTenGod, fv.pillars?.month?.stemTenGod, fv.pillars?.month?.branchMainTenGod].join(" ")),
    score: () => 78,
    buildFact: (fv) => fact({
      id: "wealth_visible_year_month",
      label: "年月财星有迹",
      meaning: "钱财更偏家庭背景、长期资源、现实责任和固定承载",
      score: 78,
      domains: ["wealth", "parents", "property"],
      category: "ten_god",
      specificity: "high",
      evidence: [`年柱${fv.pillars?.year?.label || ""}、月柱${fv.pillars?.month?.label || ""}见财星线索`],
      tags: ["财星", "年月", "固定承载"],
    }),
  },
  {
    id: "earth_storage_bearing",
    domains: ["wealth", "property", "parents"],
    category: "element",
    role: "support",
    match: (fv) => /丑|辰|未|戌/.test(Object.values(fv.pillars ?? {}).map((p) => p.branch).join("")),
    score: () => 70,
    buildFact: (fv) => fact({
      id: "earth_storage_bearing",
      label: "库土承载有迹",
      meaning: "固定资产、家庭资源和长期承载有观察点",
      score: 70,
      domains: ["wealth", "property", "parents"],
      category: "element",
      specificity: "high",
      evidence: [`地支见${Object.values(fv.pillars ?? {}).map((p) => p.branch).filter((b) => /丑|辰|未|戌/.test(b)).join("、")}`],
      tags: ["土", "库", "承载"],
    }),
  },
  {
    id: "output_weak",
    domains: ["children", "career"],
    category: "ten_god",
    role: "counter",
    match: (fv) => Number(fv.tenGods?.groupCounts?.output ?? 0) <= 1,
    score: () => 66,
    buildFact: () => fact({
      id: "output_weak",
      label: "原局食伤不显",
      meaning: "表达输出、作品成果和结果层不是最外放的原局主线",
      score: 66,
      domains: ["children", "career"],
      category: "ten_god",
      specificity: "high",
      polarity: "mixed",
      evidence: ["原局食伤统计较低"],
      tags: ["食伤", "输出", "结果层"],
    }),
  },
  {
    id: "officer_resource_chain",
    domains: ["career", "self", "parents", "fortune"],
    category: "combination",
    role: "main",
    match: (fv) => Number(fv.tenGods?.groupCounts?.officer ?? 0) >= 2 && Number(fv.tenGods?.groupCounts?.resource ?? 0) >= 2,
    score: (fv) => 78 + Number(fv.tenGods?.groupCounts?.officer ?? 0) + Number(fv.tenGods?.groupCounts?.resource ?? 0),
    buildFact: () => fact({
      id: "officer_resource_chain",
      label: "官印承接",
      meaning: "规则责任、资质承接和系统学习可以连成主线",
      score: 86,
      domains: ["career", "self", "parents", "fortune"],
      category: "combination",
      specificity: "high",
      evidence: ["官杀与印星同见", "规则压力有学习承接"],
      tags: ["官印", "规则", "承接"],
    }),
  },
  {
    id: "output_wealth_chain",
    domains: ["wealth", "career", "children"],
    category: "combination",
    role: "main",
    match: (fv) => Number(fv.tenGods?.groupCounts?.output ?? 0) >= 2 && Number(fv.tenGods?.groupCounts?.wealth ?? 0) >= 1,
    score: (fv) => 76 + Number(fv.tenGods?.groupCounts?.output ?? 0) * 4,
    buildFact: () => fact({
      id: "output_wealth_chain",
      label: "食伤生财",
      meaning: "技能表达、项目交付和财务转化之间有连接",
      score: 82,
      domains: ["wealth", "career", "children"],
      category: "combination",
      specificity: "high",
      evidence: ["食伤与财星同见"],
      tags: ["食伤", "财星", "项目"],
    }),
  },
  {
    id: "peer_wealth_tension",
    domains: ["wealth", "siblings", "friends"],
    category: "combination",
    role: "tension",
    match: (fv) => Number(fv.tenGods?.groupCounts?.peer ?? 0) >= 3 && Number(fv.tenGods?.groupCounts?.wealth ?? 0) >= 1,
    score: () => 76,
    buildFact: () => fact({
      id: "peer_wealth_tension",
      label: "比劫牵财",
      meaning: "钱财、同辈、合作和资源分配容易互相牵动",
      score: 76,
      domains: ["wealth", "siblings", "friends"],
      category: "combination",
      polarity: "mixed",
      evidence: ["比劫与财星同见"],
      tags: ["比劫", "财星", "合作分配"],
    }),
  },
  {
    id: "day_branch_relation",
    domains: ["spouse", "self", "movement", "health"],
    category: "relation",
    role: "tension",
    match: (fv) => (fv.relations ?? []).some((relation) => relation.affectsDayBranch),
    score: (fv) => (fv.relations ?? []).filter((relation) => relation.affectsDayBranch).length >= 2 ? 86 : 70,
    buildFact: (fv) => {
      const relations = (fv.relations ?? []).filter((relation) => relation.affectsDayBranch);
      return fact({
        id: "day_branch_relation",
        label: "日支关系触发",
        meaning: "关系宫、节奏、安全感和现实责任容易互相牵动",
        score: relations.length >= 2 ? 86 : 70,
        domains: ["spouse", "self", "movement", "health"],
        category: "relation",
        polarity: "mixed",
        specificity: relations.length >= 2 ? "high" : "medium",
        evidence: relations.map((relation) => relation.text).slice(0, 3),
        tags: ["日支", "关系", "牵动"],
      });
    },
  },
  {
    id: "month_pillar_environment",
    domains: ["parents", "career", "self"],
    category: "pillar",
    role: "base",
    match: (fv) => Boolean(fv.pillars?.month?.label),
    score: () => 58,
    buildFact: (fv) => fact({
      id: "month_pillar_environment",
      label: "月柱环境线",
      meaning: "成长环境、事业氛围和规则来源较值得看",
      score: 58,
      domains: ["parents", "career", "self"],
      category: "pillar",
      evidence: [`月柱为${fv.pillars?.month?.label}`],
      tags: ["月柱", "成长环境", "事业环境"],
    }),
  },
  {
    id: "hour_pillar_result",
    domains: ["children", "career", "fortune"],
    category: "pillar",
    role: "base",
    match: (fv) => Boolean(fv.pillars?.hour?.label),
    score: () => 56,
    buildFact: (fv) => fact({
      id: "hour_pillar_result",
      label: "时柱结果线",
      meaning: "后续成果、子女结果和长期规划有观察入口",
      score: 56,
      domains: ["children", "career", "fortune"],
      category: "pillar",
      evidence: [`时柱为${fv.pillars?.hour?.label}`],
      tags: ["时柱", "结果", "规划"],
    }),
  },
  {
    id: "element_bias",
    domains: ["health", "self", "fortune"],
    category: "element",
    role: "tension",
    match: (fv) => fv.elements?.biasLevel === "偏颇",
    score: () => 68,
    buildFact: (fv) => fact({
      id: "element_bias",
      label: "五行偏颇",
      meaning: "性格反应、体质倾向和长期心态容易有固定偏性",
      score: 68,
      domains: ["health", "self", "fortune"],
      category: "element",
      polarity: "mixed",
      evidence: [`主导五行：${(fv.elements?.dominant ?? []).join("、") || "待复核"}`],
      tags: ["五行", "偏性"],
    }),
  },
  {
    id: "water_wood_flow",
    domains: ["movement", "fortune", "self"],
    category: "element",
    role: "support",
    match: (fv) => /水木相生/.test((fv.elements?.flowChains ?? []).join(" ")),
    score: () => 62,
    buildFact: () => fact({
      id: "water_wood_flow",
      label: "水木流动",
      meaning: "信息吸收、环境适应和成长变化有连接",
      score: 62,
      domains: ["movement", "fortune", "self"],
      category: "element",
      evidence: ["五行链见水木相生"],
      tags: ["水木", "信息", "适应"],
    }),
  },
];

function groupDomains(group) {
  return {
    peer: ["self", "siblings", "friends", "wealth"],
    resource: ["self", "parents", "career", "fortune"],
    output: ["children", "career", "wealth"],
    wealth: ["wealth", "parents", "property"],
    officer: ["career", "spouse", "self"],
  }[group] ?? ["self"];
}

function groupMeaning(group) {
  return {
    peer: "自我、同辈、竞争合作和资源边界较有存在感",
    resource: "学习吸收、保护承接和系统意识较有存在感",
    output: "表达输出、作品成果和项目交付较有存在感",
    wealth: "现实资源、收入方式和承载责任较有存在感",
    officer: "规则职责、岗位压力和身份要求较有存在感",
  }[group] ?? "该十神信号较有存在感";
}

function dayMasterLabel(fv = {}) {
  const label = fv.dayMaster?.label || fv.dayMaster?.stem || "日主";
  return /日主/.test(label) ? label : `${label}日主`;
}

function fact(data) {
  return {
    polarity: "mixed",
    specificity: "medium",
    evidence: [],
    tags: [],
    ...data,
    score: Number(data.score ?? 50),
  };
}
